import { type NextPage } from "next";
import Head from "next/head";
import { z } from "zod";
import { Form } from "../components/form";
import { Input } from "../components/input";
import { Select } from "../components/select";
import { SubmitButton } from "../components/submit";
import { useZodForm } from "../hooks/useZodForm";

const schema = z.object({
  email: z.string(),
  count: z.coerce.number().min(10).max(20),
  fruit: z.union([z.literal('apple'), z.literal('orange')]),
});

const FruitMap: Record<z.infer<typeof schema>['fruit'], string> = {
  apple: 'Apple',
  orange: 'Orange',
};

const Home: NextPage = () => {
  const form = useZodForm({
    schema
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-md">
        <Form form={form} onSubmit={(data) => {
          console.log(data)

          return new Promise((res) => setTimeout(res, 3000));
        }}>
          <Input type="email" label="Email" required {...form.register('email')} />
          <Input type="number" label="Count" required {...form.register('count')} />
          <Select label="Fruit" required {...form.register("fruit")}>
            {schema.shape.fruit.options.map((op) => (
              <option key={op.value} value={op.value}>
                {FruitMap[op.value]}
              </option>
            ))}
          </Select>
          <SubmitButton>Submit</SubmitButton>
        </Form>
      </div>
    </>
  );
};

export default Home;
